apiVersion: batch/v1
kind: CronJob
metadata:
  name: rpa-cronjob-verificador-preco-gpu
spec:
  schedule: "0 9-22 * * *"
  timeZone: "America/Sao_Paulo"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      activeDeadlineSeconds: 300
      template:
        metadata:
          name: rpa-cronjob-verificador-preco-gpu
        spec:
          imagePullSecrets:
          - name: italommf-secret
          restartPolicy: Never
          containers:
            - name: rpa
              image: italommf/verificador_preco_gpu:latest
              imagePullPolicy: Always
              env:
                - name: NOME_AUTOMACAO
                  value: "verificador_preco_gpu"
